services:
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/Dockerfile
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - dev-network

  wordpress:
    build:
      context: .
      dockerfile: ./dockerfiles/wordpress/Dockerfile
    container_name: wordpress
    hostname: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
    volumes:
      - ./www:/var/www/wordpress
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
